### ISSUE TITLE
Error: Cannot find module './apePairs.json'

### ISSUE THREAD

**Issue by ayoub-a11y** [htkcodes/pairGen#2]
when running this show we need ape pair abi shall we use same as pancake pair abi

**Comment by htkcodes** [comment]
you need to create a file called apePairs.json

**Comment by rguitiayoub** [comment]
what ABI shall we put

**Comment by htkcodes** [comment]
Read the code first before running and understand what it is doing. there is already an abi.js file

**Comment by rguitiayoub** [comment]
problem already solved thanks 
but do you know why I have this issue 
"TypeError: Cannot read property 'toHexString' of undefined"

**Comment by htkcodes** [comment]
What function are you running first? Remember you need to run the function that generates the pairs initially

**Comment by rguitiayoub** [comment]
what function shall we call first

**Comment by htkcodes** [comment]
Updated the documentation
